name: Coderco Secrets CI

on:
  workflow_dispatch:   # lets you trigger manually
  push:                # also runs on any push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use secrets
        run: echo "The secret is ${{ secrets.MY_SECRET }}"







