name: Coderco Secrets CI

on:
  workflow_dispatch:    # lets you manually trigger it
  push:                 # still runs when you push code

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use secrets
        run: echo "The secret is ${{ secrets.MY_SECRET }}"





